# -*- coding: utf-8 -*-
"""diseased_or_not_cnn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugrzYyWFIDOEwLHG6EkmDWBG0QPBXD2Y
"""

import zipfile
from google.colab import drive

drive.mount('/content/drive/')
zip_ref = zipfile.ZipFile("/content/diseaed_or_not.zip", 'r')
zip_ref.extractall()
zip_ref.close()

import matplotlib.pyplot as plt

from keras.layers import Conv2D, Activation, GlobalAvgPool2D, MaxPooling2D, Dense, Flatten, Dropout

from keras.models import Sequential

file1='/content/data/train'

file2='/content/data/val'

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.05,
                                   zoom_range = 0.05,
                                   horizontal_flip = True)

train_set = train_datagen.flow_from_directory(file1,
                                                 target_size = (384, 384),
                                                 batch_size = 16,
                                                 class_mode = 'categorical')

import tensorflow as tf

test_datagen = ImageDataGenerator(rescale = 1./255)

test_set = test_datagen.flow_from_directory(file2,
                                            target_size = (384, 384),
                                            batch_size = 16,
                                            class_mode = 'categorical')

cnn = tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Dense(4, activation='relu', input_shape=[384,384,3]))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=[2,2], strides=2, padding='valid'))
cnn.add(tf.keras.layers.Conv2D(64, kernel_size=[2,2], padding='valid', activation='relu'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=[2,2], strides=2, padding='valid'))
cnn.add(tf.keras.layers.Conv2D(64, kernel_size=[2,2],padding='valid', activation='relu' ))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size=[2,2], strides=2, padding='valid'))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(4, activation='sigmoid'))
cnn.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

cnn.summary()

history = cnn.fit(train_set, validation_data =test_set, epochs=20, verbose=2)

plt.figure(figsize =(6,4))
plt.plot(history.history['val_loss'])
plt.title('Validation Loss')
plt.show()

plt.figure(figsize =(6,4))
plt.plot(history.history['loss'])
plt.title('Training loss')
plt.show()

plt.figure(figsize =(6,4))
plt.plot(history.history['accuracy'])
plt.title("Training Accuracy")
plt.show()

plt.figure(figsize =(6,4))
plt.plot(history.history['val_accuracy'])
plt.title("Validation Accuracy")
plt.show()

import numpy as np

import cv2

import matplotlib.pyplot as plt

import numpy as np


x = plt.imread('/content/data/test/diseased cotton leaf/dis_leaf (124).jpg')
plt.imshow(x)

x = x/255

x = np.resize(x,(1,384,384,3))

x.shape

classes = list(train_set.class_indices)

print(classes[np.argmax(cnn.predict(x))])

y = plt.imread('/content/data/test/diseased cotton plant/dd (706).jpg')
plt.imshow(y)

y = y/255

y = np.resize(y,(1,384,384,3))

y.shape

classes = list(train_set.class_indices)

print(classes[np.argmax(cnn.predict(y))])